
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smallbiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
